### PR TITLE
lookup subdomain with localhost option

### PR DESCRIPTION
**Pull request by handbremse**
#### Checklist

- [ x] only relevant code is changed (make a diff before you submit the PR)
- [x ] run tests `npm run test`
- [ ] tests are included
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [ ] only relevant documentation part is changed (make a diff before you submit the PR)
- [ ] motivation/reason is provided
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adrai** [comment]
Can you also add a test?

**Comment by handbremse** [comment]
.. but I have no clue about ```options.lookupFromSubdomainIndex```
.. what is the goal of this property?
.. i never seen such url ```https://www.uk.foot-print-on-the-moon.org``` who actually use lang subdomains in the middle of a url?

**Comment by adrai** [comment]
was introduced in https://github.com/i18next/i18next-browser-languageDetector/commit/3f30f5b76eb72239a450474d744863e3269fa2c0 by @terhuerne

**Comment by terhuerne** [comment]
@handbremse The idea of this property was to be more flexible with the subdomain mapping. For instance a localized subdomain. Given:

https://partners.de.domain.com

In this case, the partners page can be localized through this subdomain. While this is not the most common case, we've seen this pattern in some business applications and therefore I've added this feature. As this is optional, I don't see an issue to keep it as a feature for those who need it.

**Comment by adrai** [comment]
@terhuerne is this PR approved from your side?
Can we merge it like that?

**Comment by terhuerne** [comment]
Yes, looks good.

**Comment by adrai** [comment]
Thank you @handbremse (and @terhuerne)... this was now released with v6.1.5.

**Pull request merged**
