### PR TITLE
drop locale if "languageOnly" is set

### PR DESCRIPTION
**Pull request by PatrickHeneise**
There is a config option `load: languageOnly` on i18next, but this option isn't used in the detector. In localStorage and the cookie `en-US` is stored.

Use:

options: `languageOnly: true`

### CODE REVIEW

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L84

the detector always detect the most explicit defined language and store that -> i18next will use the above function to define the languages it should load and use for translation fallback...

**Comment by PatrickHeneise** [comment]
Ok ... so if I don't care about the locale and only the language, but localStorage is set to `en-US`, it's kind of hard to work with that. The change requires an additional option to be set to true, so it doesn't change existing behaviour.

**Comment by jamuhl** [comment]
why you need this...what is your use case? it's irrelevant if it stores `en` or `en-US` in localStorage...i18next does the right thing with the `languageOnly` setting

**Comment by PatrickHeneise** [comment]
We have a bunch of different places where we use and change the language (header, footer, user profile, ...). For example a dropdown with options 'en', 'de', etc. _After_ i18n.init(), everything is just 'xx', as the `languageOnly` option removes the locale. But the navigator detector writes `xx-YY` to localStorage and cookie which is inconsistent with this setting. This means some hacking after init() and before everything else to remove the locale, so just removing the locale in the first place makes a lot of sense.

I should have started this conversation with an issue, my apologies!

**Comment by jamuhl** [comment]
there is no inconsistency...also if you call i18next.changeLanguage it will store what ever you pass...and do the right thing...

actually where do you have an issue beside localstorage has a more specific language set than your translations are resolved to?

**Comment by jamuhl** [comment]
anyway...i18next does work correctly independent of this PR -> but: no one will force you to use the "official" langugage detector - you can use your own removing region from detected language.

**Comment by PatrickHeneise** [comment]
Using i18next.changeLanguage stores `en` in localStorage, the detector stored `en-US`, so this is clearly inconsistent when I set the option `languageOnly`.

I tried to make this change simple, opt-in and non-breaking, is there anything else I can do to get this merged? I don't want to maintain our fork just to keep the locale out of localStorage and I don't want to hack around the issue in our code either. This is the easiest fix for the issue.

**Comment by jamuhl** [comment]
The point I see this not as an issue - there is nothing broken. The value stored in localStorage is for i18next usage -> if there is stored `en-US` or `en` makes no difference when `languageOnly` is set...

the change might be non breaking and opt-in -> but needs to be added to all the other detectors out there to keep them consistent...

**Comment by PatrickHeneise** [comment]
Alright. I don't know the implications of merging this enhancement so I guess we'll have to maintain our fork to keep a solution to the issue, since I don't want to check with every use of the localStorage value if it has a dash in it or not.

**Comment by jamuhl** [comment]
The question really is ... why do you need to check that? You should not access / use the value in localstorage...use i18next.languages[0] if needing the used language only

**Pull request closed without merging**
