### PR TITLE
sessionStorage support

### PR DESCRIPTION
**Pull request by udf2457**
### Checklist

- [ X ] only relevant code is changed (make a diff before you submit the PR)
- [ X  ] run tests `npm run test`
- [  X ] tests are included
- [ ] documentation is changed or added

Pull request for sessionStorage.  I'm still a bit of a JS newbie, so I hope they're ok !

```
> i18next-browser-languagedetector@4.2.0 pretest /Users/udf2457/i18next-browser-languageDetector
> npm run test:typescript && npm run test:typescript:noninterop


> i18next-browser-languagedetector@4.2.0 test:typescript /Users/udf2457/i18next-browser-languageDetector
> tslint --project tsconfig.json


> i18next-browser-languagedetector@4.2.0 test:typescript:noninterop /Users/udf2457/i18next-browser-languageDetector
> tslint --project tsconfig.nonEsModuleInterop.json


> i18next-browser-languagedetector@4.2.0 test /Users/udf2457/i18next-browser-languageDetector
> npm run build && mocha test -R spec --exit


> i18next-browser-languagedetector@4.2.0 build /Users/udf2457/i18next-browser-languageDetector
> rimraf dist && rollup -c && cpy "./dist/umd/*.js" ./


./src/index.js → ./dist/cjs/i18nextBrowserLanguageDetector.js...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
created ./dist/cjs/i18nextBrowserLanguageDetector.js in 491ms

./src/index.js → ./dist/esm/i18nextBrowserLanguageDetector.js...
created ./dist/esm/i18nextBrowserLanguageDetector.js in 202ms

./src/index.js → dist/umd/i18nextBrowserLanguageDetector.js...
created dist/umd/i18nextBrowserLanguageDetector.js in 142ms

./src/index.js → dist/umd/i18nextBrowserLanguageDetector.min.js...
created dist/umd/i18nextBrowserLanguageDetector.min.js in 386ms


  language detector
    cookie
      ✓ detect
      ✓ cacheUserLanguage
    path
      ✓ detect
    querystring
      ✓ detect


  4 passing (6ms)
```

### CODE REVIEW

**Comment by adrai** [comment]
Can you update the Readme too?

**Comment by udf2457** [comment]
Do you want me to close & reopen the PR or will you just pull the updated readme from the fork?

**Comment by adrai** [comment]
released in v4.3.0

**Comment by khownz** [comment]
@udf2457 I've noticed that it only appears to be working when you add `lookupsessionStorage` to the options.

1. This should probably be `lookupSessionStorage` (capital S), to match the other prop names.
2. `localStorage` seems to be working with a default `i18nextLng` when it is added to the `order` array and there is no `lookupLocalStorage` set. We should probably match this behaviour.

**Comment by adrai** [comment]
I think this is intended, because it is not added by default: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L16
@udf2457 what is your opinion?

**Comment by udf2457** [comment]
@adrai I'd love to have an opinion, but unfortunately I've moved on to other work and have not spent much time with i18next in recent months.

My guess @adrai is you are probably right in your observation. I'm not exactly a JS guru, so if this relates to the code you pulled in from me, it is quite possible I omited something.

P.S. Whilst I'm here, I agree with @khownz, consistency is good.  If you're going to use camel-case, then use it everywhere.

**Comment by adrai** [comment]
@khownz do you like to submit a PR?

**Comment by khownz** [comment]
@adrai will do!

1. Change `lookupSessionStorage` to be camelCased
2. Add a default for `lookupSessionStorage`
3. Update readme

**Comment by khownz** [comment]
#221

**Comment by adrai** [comment]
fyi, released in v6.0.0

**Pull request merged**
